# @package _global_

experiment:
  visdom_ip: localhost
  name: M2ED_HigherHRNet
  batch_size: 16
  workers: 2


trainer:
  gpus: "0"
  max_epochs: 45
  limit_train_batches: 1.
  limit_val_batches: 1.
  deterministic: true
  checkpoint:
    monitor: val_npe
    filename: '{epoch}-{npe:.2f}'

engine:
  modules:
    manual_seed:
      seed: 1989
      deterministic: true

logging:
  name: ${experiment.name}
  loggers:
    visdom:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      clear_window: False
    tabular:
      name: ${experiment.name}


visualization:
  batch_interval: 50
  visualizers:
    gizmo2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      images: [exocentric_0_colour]
      gizmos: [marker_diamond]
      gt: [exocentric_0_points_3d]
      pred: [projected_kpts_est]
      coords: [coord]
      color_gt: [red]
      color_pred: [orange]
      reverse_coords: [true]
    
    feature2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      keys: [heatmaps_gt_1,heatmaps_t_1]
      types: [color,color]
      colormaps: [turbo,turbo]
      transforms: [minmax,minmax]
