engine:
  _target_: moai.engine.Engine
  modules:
    manual_seed:
      _target_: moai.engine.modules.ManualSeed
      seed: 1989
      deterministic: false
trainer:
  _target_: moai.engine.lightning.train.LightningTrainer
  max_epochs: 45
  min_epochs: 1
  check_val_every_n_epoch: 1
  gradient_clip_val: 0.0001
  accumulate_grad_batches: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  val_check_interval: 1.0
  reload_dataloaders_every_epoch: false
  deterministic: false
  auto_lr_find: false
  terminate_on_nan: false
  auto_scale_batch_size: false
  automatic_optimization: true
  num_nodes: 0
  num_processes: 1
  precision: 32
  benchmark: false
  auto_select_gpus: false
  amp_backend: native
  amp_level: O2
  prepare_data_per_node: true
  replace_sampler_ddp: true
  flush_logs_every_n_steps: 100
  log_every_n_steps: 10
  progress_bar_refresh_rate: 1
  weights_summary: full
  profiler: simple
  default_root_dir: ''
  fast_dev_run: false
  num_sanity_val_steps: 2
  track_grad_norm: -1
  process_position: 0
  checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_npe
    verbose: false
    save_weights_only: false
    mode: auto
    period: 1
    prefix: ${experiment.name}
    save_top_k: 3
    save_last: true
    dirpath: null
    filename: '{epoch}-{npe:.2f}'
  regularization:
    _target_: moai.parameters.regularization.lightning.NoOp
  gpus: '3'
  resume_from_checkpoint: G:\VCL\Users\galbanis\reproducibility\conf_files\Tello\outputs\train\2021-01-16\21-31-25-Tello_hrnet_heatmap_loss\Tello_hrnet_heatmap_loss\0_0\checkpoints\Tello_hrnet_heatmap_loss-last.ckpt
visualization:
  _target_: moai.visualization.Collection
  batch_interval: 50
  visualizers:
    feature2d:
      _target_: moai.visualization.visdom.Feature2d
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      keys:
      - heatmaps_gt
      - heatmaps_t_4
      types:
      - color
      - color
      colormaps:
      - turbo
      - turbo
      transforms:
      - minmax
      - minmax
    gizmo2d:
      _target_: moai.visualization.visdom.Gizmo2d
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      images:
      - exocentric_0_colour
      gizmos:
      - marker_diamond
      gt:
      - exocentric_0_points_3d
      pred:
      - projected_kpts_est
      coords:
      - coord
      color_gt:
      - red
      color_pred:
      - orange
      reverse_coords:
      - true
logging:
  _target_: moai.log.lightning.Collection
  name: ${experiment.name}
  loggers:
    visdom:
      _target_: moai.log.lightning.loggers.Visdom
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      clear_window: false
    tabular:
      _target_: moai.log.lightning.loggers.Tabular
      name: ${experiment.name}
data:
  train:
    loader:
      _target_: torch.utils.data.DataLoader
      batch_size: ${experiment.batch_size}
      shuffle: true
      num_workers: ${experiment.workers}
      pin_memory: false
      drop_last: false
    iterator:
      _target_: moai.data.iterator.Indexed
      augmentation:
        _target_: moai.data.augmentation.NoOp
      datasets:
        UAVA:
          _target_: moai.data.datasets.object_pose.UAVA
          root: ${root}
          metadata: ${metadata}
          split: train
          views:
          - exocentric
          drones:
          - Tello
          frames:
          - 0
          types:
          - colour
  test:
    loader:
      _target_: torch.utils.data.DataLoader
      batch_size: ${experiment.batch_size}
      shuffle: false
      num_workers: ${experiment.workers}
      pin_memory: false
      drop_last: false
    iterator:
      _target_: moai.data.iterator.Indexed
      augmentation:
        _target_: moai.data.augmentation.NoOp
      datasets:
        UAVA:
          _target_: moai.data.datasets.object_pose.UAVA
          root: ${root}
          metadata: ${metadata}
          split: test
          views:
          - exocentric
          drones:
          - Tello
          frames:
          - 0
          types:
          - colour
  val:
    loader:
      _target_: torch.utils.data.DataLoader
      batch_size: ${experiment.batch_size}
      shuffle: false
      num_workers: ${experiment.workers}
      pin_memory: true
      drop_last: false
    iterator:
      _target_: moai.data.iterator.Indexed
      augmentation:
        _target_: moai.data.augmentation.NoOp
      datasets:
        UAVA:
          _target_: moai.data.datasets.object_pose.UAVA
          root: ${root}
          metadata: ${metadata}
          split: test
          views:
          - exocentric
          drones:
          - Tello
          frames:
          - 0
          types:
          - colour
model:
  _target_: moai.networks.lightning.factory.HRNet
  configuration:
    stages: 3
    in_features: 3
    out_features: 9
    input: exocentric_0_colour
    output: heatmaps_t_4
    preproc:
      stem:
        blocks:
        - conv2d
        - conv2d
        convolutions:
        - conv2d
        - conv2d
        activations:
        - bn2d_relu
        - bn2d_relu
        kernel_sizes:
        - 3
        - 3
        features:
        - 64
        - 64
        strides:
        - 2
        - 2
        paddings:
        - 1
        - 1
      residual:
        block: preactiv_bottleneck
        convolution: conv2d
        activation: bn2d_relu
        features:
          in_features:
          - 64
          - 256
          - 256
          - 256
          out_features:
          - 256
          - 256
          - 256
          - 256
          bottleneck_features:
          - 64
          - 64
          - 64
          - 64
    branches:
      block: conv2d
      convolution: conv2d
      activation: relu
      start_features: 48
      kernel_size: 3
      stride: 1
      padding: 1
      modules:
      - 1
      - 4
      depths:
      - - 4
      - - 4
        - 4
        - 4
        - 4
    global:
      convolution: conv2d
      activation: bn2d_relu
  modules:
    highres:
      _target_: moai.modules.lightning.highres.HighResolution
      residual:
        type: preactiv_bottleneck
        bottleneck_features: 64
        convolution: ${model.configuration.global.convolution}
        activation: ${model.configuration.global.activation}
      fuse:
        convolution: ${model.configuration.global.convolution}
        activation:
          intermediate: bn2d_relu
          prefusion: bn2d
          final: relu
        upscale:
          type: upsample2d
          conv_up: true
    start_transition:
      _target_: moai.modules.lightning.highres.StartTransition
      identity:
        convolution: ${model.configuration.global.convolution}
        activation: ${model.configuration.global.activation}
        kernel_size: 3
        stride: 1
        padding: 1
      branched:
        convolution: ${model.configuration.global.convolution}
        activation: ${model.configuration.global.activation}
        downscale: none
        kernel_size: 3
        stride: 2
        padding: 1
    stage_transition:
      _target_: moai.modules.lightning.highres.StageTransition
      branched:
        convolution: ${model.configuration.global.convolution}
        activation: ${model.configuration.global.activation}
        downscale: none
        kernel_size: 3
        stride: 2
        padding: 1
    head:
      _target_: moai.modules.lightning.highres.TopBranchHead
      convolution: ${model.configuration.global.convolution}
      activation: none
      kernel_size: 1
      padding: 0
  feedforward:
    preprocess:
      _target_: moai.monads.execution.Cascade
      camera:
        x:
        - exocentric_0_colour
        out:
        - camera_matrix
      grid:
        tensor:
        - exocentric_0_colour
        out:
        - grid
      keypoints:
        x:
        - exocentric_0_colour
        out:
        - keypoints_out
      vertices:
        x:
        - exocentric_0_colour
        out:
        - vertices
      isotropic_gaussian:
        keypoints:
        - exocentric_0_points_3d
        grid:
        - grid
        out:
        - heatmaps_gt
    postprocess:
      _target_: moai.monads.execution.Cascade
      scalar:
        tensor:
        - exocentric_0_colour
        out:
        - index_0
      ones:
        tensor:
        - index_0
        out:
        - index_1
      spatial_softmax:
        tensor:
        - heatmaps_t_4
        out:
        - heatmaps_t_4
      center_of_mass:
        grid:
        - grid
        heatmaps:
        - heatmaps_t_4
        out:
        - predicted_kpts
      unit_to_coords:
        coords:
        - exocentric_0_points_3d
        - predicted_kpts
        img:
        - exocentric_0_colour
        - exocentric_0_colour
        out:
        - exocentric_0_points_3d
        - predicted_kpts
      bpnp:
        keypoints2d:
        - predicted_kpts
        intrinsics:
        - camera_matrix
        keypoints3d:
        - keypoints_out
        out:
        - predicted_pose
      split:
        tensor:
        - predicted_pose
        - predicted_pose
        index:
        - index_1
        - index_0
        out:
        - predicted_trans
        - predicted_rot
      angle_axis:
        angle_axis:
        - predicted_rot
        out:
        - predicted_rot
      transform:
        points:
        - vertices
        - vertices
        - keypoints_out
        rotation:
        - exocentric_0_rotation
        - predicted_rot
        - predicted_rot
        translation:
        - exocentric_0_translation
        - predicted_trans
        - predicted_trans
        out:
        - pts_gt
        - pts_est
        - kpts_est
      project:
        intrinsics:
        - camera_matrix
        - camera_matrix
        - camera_matrix
        points:
        - pts_gt
        - pts_est
        - kpts_est
        out:
        - projected_points_gt
        - projected_points_est
        - projected_kpts_est
  monads:
    grid:
      _target_: moai.monads.generation.grid.Grid
      mode: unit
      width: 80
      height: 60
      depth: 1
      inclusive: true
      order: xy
    camera:
      _target_: moai.monads.generation.camera.Perspective
      fov: 64.69
      width: 320
      height: 240
    keypoints:
      _target_: moai.monads.generation.keypoints.keypoints.Keypoints
      keypoints: ${keypoints}
    vertices:
      _target_: moai.monads.generation.mesh.Vertices
      filename: G:\VCL\Users\galbanis\reproducibility\metadata\Tello.obj
    isotropic_gaussian:
      _target_: moai.monads.distribution.reconstruction.IsotropicGaussian
      std: 3.5
      normalize: true
      scale: true
      grid_type: unit
    scalar:
      _target_: moai.monads.generation.tensor.Scalar
      value: 0
    ones:
      _target_: moai.monads.generation.tensor.Ones
    center_of_mass:
      _target_: moai.monads.distribution.CenterOfMass
      mode: default
      flip: false
    spatial_softmax:
      _target_: moai.monads.distribution.prior.SpatialSoftmax
      temperature: 1.0
      alpha: 1.0
      normalize: false
    unit_to_coords:
      _target_: moai.monads.object_pose.UnitToCoords
      flip: true
    bpnp:
      _target_: moai.monads.object_pose.bpnp.BPnP
      isBatch: true
      transpose: false
    split:
      _target_: moai.monads.tensor.Split
      dim: 1
      split: 0
    angle_axis:
      _target_: moai.monads.object_pose.AngleAxis
      convert_to: rot_mat
    transform:
      _target_: moai.monads.geometry.Transformation
      xyz_in_at: row
      xyz_out_at: channel
      transpose: false
    project:
      _target_: moai.monads.geometry.Projection
      xyz_at: channel
      uv_at: row
      uv_type: coord
  parameters:
    initialization:
      _target_: moai.parameters.initialization.Default
    optimization:
      _target_: moai.parameters.optimization.Single
      optimizers:
        adam:
          _target_: torch.optim.Adam
          lr: 0.0001
          betas:
          - 0.9
          - 0.999
          eps: 1.0e-08
          weight_decay: 0.0
          amsgrad: false
  supervision:
    _target_: moai.supervision.Weighted
    losses:
      L1:
        _target_: moai.supervision.losses.regression.L1
      L2:
        _target_: moai.supervision.losses.regression.L2
    L1:
      gt:
      - heatmaps_gt
      pred:
      - heatmaps_t_4
      out:
      - L1
    L2:
      gt:
      - exocentric_0_points_3d
      pred:
      - projected_kpts_est
      weight:
      - 1.0e-05
      out:
      - projection
  validation:
    _target_: moai.validation.Collection
    metrics:
      object_pose_position:
        _target_: moai.validation.metrics.object_pose.NormalizedPositionError
      object_pose_rotation:
        _target_: moai.validation.metrics.object_pose.AngleError
      object_pose_accuracy2:
        _target_: moai.validation.metrics.object_pose.Accuracy2
      object_pose_accuracy5:
        _target_: moai.validation.metrics.object_pose.Accuracy5
      object_pose_accuracy10:
        _target_: moai.validation.metrics.object_pose.Accuracy10
      object_pose_add2:
        _target_: moai.validation.metrics.object_pose.SixD2
        diagonal: ${diagonal}
      object_pose_add5:
        _target_: moai.validation.metrics.object_pose.SixD5
        diagonal: ${diagonal}
      object_pose_add10:
        _target_: moai.validation.metrics.object_pose.SixD10
        diagonal: ${diagonal}
      object_pose_projection2:
        _target_: moai.validation.metrics.object_pose.Projection2
      object_pose_projection5:
        _target_: moai.validation.metrics.object_pose.Projection5
      object_pose_projection10:
        _target_: moai.validation.metrics.object_pose.Projection10
    object_pose_position:
      pred:
      - predicted_trans
      gt:
      - exocentric_0_translation
      out:
      - npe
    object_pose_rotation:
      pred:
      - predicted_rot
      gt:
      - exocentric_0_rotation
      out:
      - angular_error
    object_pose_accuracy2:
      pred_rotation:
      - predicted_rot
      gt_rotation:
      - exocentric_0_rotation
      pred_position:
      - predicted_trans
      gt_position:
      - exocentric_0_translation
      out:
      - acc2
    object_pose_accuracy5:
      pred_rotation:
      - predicted_rot
      gt_rotation:
      - exocentric_0_rotation
      pred_position:
      - predicted_trans
      gt_position:
      - exocentric_0_translation
      out:
      - acc5
    object_pose_accuracy10:
      pred_rotation:
      - predicted_rot
      gt_rotation:
      - exocentric_0_rotation
      pred_position:
      - predicted_trans
      gt_position:
      - exocentric_0_translation
      out:
      - acc10
    object_pose_add2:
      pts_gt:
      - pts_gt
      pts_est:
      - pts_est
      out:
      - add2
    object_pose_add5:
      pts_gt:
      - pts_gt
      pts_est:
      - pts_est
      out:
      - add5
    object_pose_add10:
      pts_gt:
      - pts_gt
      pts_est:
      - pts_est
      out:
      - add10
    object_pose_projection2:
      gt:
      - projected_points_gt
      pred:
      - projected_points_est
      out:
      - proj2d_2px
    object_pose_projection5:
      gt:
      - projected_points_gt
      pred:
      - projected_points_est
      out:
      - proj2d_5px
    object_pose_projection10:
      gt:
      - projected_points_gt
      pred:
      - projected_points_est
      out:
      - proj2d_10px
root: D:\Data\FASTER\
metadata: G:\VCL\Users\galbanis\reproducibility\metadata\annot_merged_new.txt
keypoints:
- - 0.0
  - 0.0
  - 0.0
- - 0.0467
  - 0.0199
  - 0.036
- - -0.0477
  - 0.0203
  - 0.0355
- - 0.0476
  - -0.0311
  - 0.0349
- - -0.047
  - -0.0311
  - 0.036
- - 0.047
  - 0.0186
  - -0.0359
- - -0.0489
  - 0.0199
  - -0.037
- - 0.0476
  - -0.0311
  - -0.0371
- - -0.0464
  - -0.0311
  - -0.0377
experiment:
  visdom_ip: localhost
  name: Tello_hrnet_mixture_e003
  batch_size: 24
  workers: 4
downscale_type: maxpool2d_aa
upscale_type: upsample2d
diagonal: 0.219485
mode: train
